### ISSUE TITLE
Current releases of marctv/overviewer113 via Dockerhub are missing parts of overviewer source.

### ISSUE THREAD

**Issue by melair** [mtoensing/Docker-Minecraft-Overviewer#1]
Greetings @mtoensing!

I've been trying to your Docker container this working for 1.13.X rendering. However it seems like some of the overviewer code is missing from the built Docker container.

```
peter@rubidium:~/overviewer$ docker image ls | grep overviewer
marctv/overviewer113                                                latest              ee3df7992ff7        5 hours ago         495MB
```

When I execute:

```
docker run --rm -v /home/peter/caldonia/world/:/tmp/world/:ro -v /home/peter/overviewer/config/:/tmp/config/:ro -v /home/peter/overviewer/output/:/tmp/export/:rw -it marctv/overviewer113
```

I see

```
peter@rubidium:~/overviewer$ sh run.sh
Traceback (most recent call last):
  File "/tmp/overviewer/overviewer.py", line 41, in <module>
    from overviewer_core import configParser, tileset, assetmanager, dispatcher
  File "/tmp/overviewer/overviewer_core/configParser.py", line 7, in <module>
    import settingsDefinition
ImportError: No module named settingsDefinition
```

Indeed looking inside the container, suggests that settingsDefinition.py (and a few others) are not present in the copy inside the container, but are in the minecraft113 branch of overviewer. Is it worth doing a git clone in the Dockerfile via a RUN, rather than a static copy?

```
peter@rubidium:~/overviewer$ docker run --rm -v /home/peter/caldonia/world/:/tmp/world/:ro -v /home/peter/overviewer/config/:/tmp/config/:ro -v /home/peter/overviewer/output/:/tmp/export/:rw --entrypoint= -it marctv/overviewer113 ls -la /tmp/overviewer/overviewer_core
total 1384
drwxr-xr-x 1 root root   4096 Feb  3 10:30 .
drwxr-xr-x 1 root root   4096 Feb  3 10:30 ..
-rwxr-xr-x 1 root root   2840 Feb  3 10:24 __init__.py
-rw-r--r-- 1 root root   2355 Feb  3 10:29 __init__.pyc
-rwxr-xr-x 1 root root   9377 Feb  3 10:24 assetmanager.py
drwxr-xr-x 2 root root   4096 Feb  3 10:24 aux_files
-rwxr-xr-x 1 root root 852152 Feb  3 10:30 c_overviewer.so
-rwxr-xr-x 1 root root   4521 Feb  3 10:24 cache.py
-rwxr-xr-x 1 root root   5832 Feb  3 10:24 configParser.py
drwxr-xr-x 5 root root   4096 Feb  3 10:24 data
-rwxr-xr-x 1 root root  15059 Feb  3 10:24 dispatcher.py
-rwxr-xr-x 1 root root   7186 Feb  3 10:24 files.py
-rwxr-xr-x 1 root root   8934 Feb  3 10:24 items.py
-rwxr-xr-x 1 root root  10916 Feb  3 10:24 logger.py
-rwxr-xr-x 1 root root  11030 Feb  3 10:24 nbt.py
-rwxr-xr-x 1 root root  15661 Feb  3 10:24 observer.py
-rwxr-xr-x 1 root root   6801 Feb  3 10:24 optimizeimages.py
-rw-r--r-- 1 root root    159 Feb  3 10:29 overviewer_version.py
-rwxr-xr-x 1 root root  13658 Feb  3 10:24 progressbar.py
-rwxr-xr-x 1 root root   2762 Feb  3 10:24 rcon.py
-rwxr-xr-x 1 root root   8187 Feb  3 10:24 rendermodes.py
-rwxr-xr-x 1 root root   3998 Feb  3 10:24 signals.py
drwxr-xr-x 1 root root   4096 Feb  3 10:29 src
-rwxr-xr-x 1 root root 201641 Feb  3 10:24 textures.py
-rwxr-xr-x 1 root root  72335 Feb  3 10:24 tileset.py
-rwxr-xr-x 1 root root  13522 Feb  3 10:24 util.py
-rw-r--r-- 1 root root  13943 Feb  3 10:29 util.pyc
-rwxr-xr-x 1 root root  65562 Feb  3 10:24 world.py
```

Any thoughts?

**Comment by melair** [comment]
For example:

https://github.com/melair/Docker-Overviewer-1.13.1/commit/455da0d406cc8c030e7556e3ef13a89a88b7cd02#diff-3254677a7917c6c01f55212f86c57fbf

That now runs on my machine from a clean build of the container.

**Comment by melair** [comment]
k, take that back, it doesn't run flawlessly. I'm guessing there are some differences between official repo and the one in COPY?

**Comment by mtoensing** [comment]
Hi! Thank you so much! You found the root cause of a lot of weird things. I intentionally copied the files because I patched many files because the 113 branch did not receive any merges anymore. 

But I left the .gitignore from the original repository in there. That prevented some files being pushed. Such as settingsDefinition.py. But my image in dockerhub https://hub.docker.com/r/marctv/overviewer113/ worked. The reason was that I pushed that locally. 

Could you please pull again and check if it is working now?

**Comment by melair** [comment]
Ello!

Yup, that's got it. Working great now, thank you for taking the time out to build it.

Glad to have helped.

M.

**Comment by mtoensing** [comment]
Thank you!
